#!/bin/bash

pushd ~/.vim
git submodule init
git submodule update

pushd ~/.vim/bundle/command-t/ruby/command-t
ruby extconf.rb
make
popd

# move any existing files (but overwrite existing symlinks)
TIMESTAMP=$(date +'%Y-%m-%d_%H:%M:%S')
filenames=(vimrc gvimrc)
for filename in "${filenames[@]}"
do
    if [[ -e ~/.$filename && ! -h ~/.$filename ]]
    then
        mv ~/.$filename  ~/.$filename$TIMESTAMP
    fi
done

ln -sf ~/.vim/vimrc ~/.vimrc
ln -sf ~/.vim/gvimrc ~/.gvimrc
popd
