#!/bin/bash

pushd ~/.vim
git submodule init
git submodule update

pushd ~/.vim/bundle/command-t
rake make
popd

mv ~/.vimrc ~/.vimrc.bak
mv ~/.gimrc ~/.vimrc.bak

ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc
popd
