#!/bin/bash

pushd ~/.vim
git submodule init
git submodule update

pushd ~/.vim/bundle/command-t
rake make
popd

# move any existing files
TIMESTAMP=$(date +'%Y-%m-%d_%H:%M:%S')
ls ~/.vimrc && mv ~/.vimrc ~/.vimrc.bak$TIMESTAMP
ls ~/.gvimrc && mv ~/.gvimrc ~/.gvimrc.bak$TIMESTAMP

ln -s ~/.vim/vimrc ~/.vimrc
ln -s ~/.vim/gvimrc ~/.gvimrc
popd
