#!/bin/bash

# Show git banch.
__parse_git_branch() {
    type git >/dev/null 2>&1
    if [ "$?" -ne 0 ]; then
        return
    fi

    # Quit if this is not a Git repo.
    local branch=$(git symbolic-ref HEAD 2> /dev/null)
    if [[ -z $branch ]] ; then
        # attempt to get short-sha-name
        branch=":$(git rev-parse --short HEAD 2> /dev/null)"
    fi
    if [ "$?" -ne 0 ]; then
        # this must not be a git repo
        return
    fi

    # Clean off unnecessary information.
    branch=${branch##*/}
    echo $branch
}

libdir=$(dirname $0)
source "$libdir/tmux_adapter.sh"

branch_symbol="⭠"

pwd="$(_tmux_get_var pwd)"
cd "$pwd"
branch=$(__parse_git_branch)

if [ -n "$branch" ]
then
    echo "$branch_symbol $branch"
fi
